# Generated by Django 5.0.4 on 2024-04-17 07:35

import TastyRecipesApp.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[TastyRecipesApp.profiles.models.starts_with_capital_validator])),
                ('last_name', models.CharField(max_length=30, validators=[TastyRecipesApp.profiles.models.starts_with_capital_validator])),
                ('nickname', models.CharField(error_messages={'unique': 'Nickname must be unique!'}, max_length=20, unique=True, validators=[TastyRecipesApp.profiles.models.min_length_2_validator])),
                ('chef', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
